apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
    etcd_node: etcd0
  name: etcd0
spec:
  containers:
  - command:
    - /usr/local/bin/etcd
    - --name
    - etcd0
    - --initial-advertise-peer-urls
    - http://etcd0:2380
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://etcd0:2379
    - --initial-cluster
    - etcd0=http://etcd0:2380
    - --initial-cluster-state
    - new
    image: quay.io/coreos/etcd:v3.4.16
    name: etcd0
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
    readinessProbe:
      httpGet:
        path: /health
        port: 2379
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /health
        port: 2379
      initialDelaySeconds: 15
      periodSeconds: 20
  restartPolicy: Always
  securityContext:
    fsGroup: 1000


---
apiVersion: v1
kind: Service
metadata:
  name: etcd-for-vineyard
  labels:
    app: etcd
spec:
  ports:
  - name: etcd-for-vineyard-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
